import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import localFont from 'next/font/local'

const Gabarito = localFont({ src: '../../../fonts/Gabarito-Black.ttf' })
// import { Gabarito } from '../../../fonts/Gabarito-Black.ttf'
import { Poppins } from 'next/font/google'

// const gabarito = Gabarito({
//   weight: ['900'],
//   style: ['normal'],
//   subsets: ['latin']
// })
const poppins = Poppins({
  weight: ['500', '700'],
  style: ['normal'],
  subsets: ['latin']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function FormLayout({ children }) {
  return (
    <div id="formBody">
      <section id="formSiding">
        <div id="formInfoHeading">
          <div className="relative">
            <h1 className="contestInfo evilInfo" aria-hidden="true">CONTEST INFO</h1>
            <h1 className="contestInfo ">CONTEST INFO</h1>
          </div>
          <button id="formInfoPopup">i</button>
        </div>
          <div id="formSidingContainer">
          <p className="paragraphText"> </p>
          <p className="paragraphText">
            1. Fill out the form with your details.<br/>
            2. Spin the wheel and see if you're a winner!<br/>
            3. Winners will be notified by email and must correctly answer a skill-testing question to claim their prize.<br/>
          </p><br/>
          <p className="paragraphText">
          Winners will be selected by random draw. BuyMore Dollars Inc. reserves the right to remove any entries at their discretion.* By entering, you agree to the contest rules and regulations and consent to receive communications from BuyMore Dollars and our sponsors.
          </p>
        </div>
        <div id="formSidingBodyParagraph">
          <p className="paragraphText bottom">
            *Prizes are subject to adherent contest rules and regulations.Delivery timelines may vary, with an estimated arrival of 60-90 days]. BuyMore Dollars Inc. reserves the right to remove any entries at their discretion.  [*Prizes are subject to adherent contest rules and regulations.Delivery timelines may vary, with an estimated arrival of 60-90 days] By entering, you agree to the contest rules and regulations and consent to receive communications from BuyMore Dollars and our sponsors.
          </p>
        </div>
      </section>
      <div id="formContent">
        {children}
      </div>
    </div>
  );
}
